name: audio_processing_gpu  # Consistent name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Or your Python version
  - asttokens=2.4.1
  - audioread=3.0.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24  # Update if needed
  - certifi=2024.8.30      # Update if needed
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - debugpy=1.8.8
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.13.1
  - fonttools=4.55.0
  - freetype=2.12.1
  - gmpy2=2.1.2
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lcms2=2.15
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libflac=1.4.3
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - librosa=0.10.2.post1
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libtiff=4.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxml2=2.13.1
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.32.9
  - mpir=3.0.0
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nltk=3.9.1
  - numba=0.60.0
  - numpy=2.0.2
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=11.0.0
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydub=0.25.1
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pywin32=307
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - regex=2024.11.6
  - requests=2.32.3
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - setuptools=75.1.0
  - six=1.16.0
  - soxr=0.1.3
  - soxr-python=0.5.0.post1
  - speechrecognition=3.11.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.67.0
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14